### ISSUE TITLE
Regarding rating inaccuracy

### ISSUE THREAD

**Issue by Imsvale** [BenTheDan/IngameRank#2]
Hello!

I'm inquiring regarding the rating inaccuracy currently described on the [mod page](https://bakkesplugins.com/plugins/view/282). I was wondering if you could put me in contact with the person(s) reporting to you these inaccuracies, to find out where exactly the inaccuracies are, and what changes would need to be made, if any. 

I've gone over the [skill distribution data on TRN](https://rocketleague.tracker.network/rocket-league/distribution?playlist=10) for 1v1, 2v2 and 3v3, and cross-checked with the [chart](https://www.reddit.com/r/RocketLeague/comments/msik3b/season_3_ftp_mew_mmr_chart/) by Reddit user [marcxb89](https://www.reddit.com/user/marcxb89), which to my knowledge is the most up to date source of rank thresholds outside of the tracker, and I can't find any significant deviations. Of course the TRN data isn't entirely accurate to begin with, due to the nature of how the data is generated (only looking at currently tracked players).

The changes to the ratings you describe, are unknown to me, especially the suggested method of change. I'm attempting to verify with other users who know more. If rank thresholds are now updated seasonally, that would be a pretty fundamental change.

There is a slight bug in the Ingame Rank display, in that it will sometimes swap the rank icons (but not divisions) of different players on the same team. You look once and you appear to be playing against a C3d4 and a C2d1, but it turns out they're actually C3d1 and C2d4 (which if I'm high C2 makes much more sense matchmaking-wise). I'm wondering if this has confused the person who reported this to you, into believing the rank assignments themselves are inaccurate. Not knowing any details about this, of course I'm just speculating.

That's why I was hoping, even if you don't mean to make any changes to the mod anymore, that you would help with some more information on the issue so we can find out what's what.

Thanks!

**Comment by BenTheDan** [comment]
Hey,

Thanks for writing. It is very much possible that my assumptions about the inaccuracies are flawed. Honestly I didn't really care to check, since I barely really play RL anymore, and just added the disclaimer.

I'm not really sure where this idea of changing thresholds came from, but I believe you have already researched it way more than I have. If you say the ratings are accurate I believe you. My assumptions were not exactly based on the most reliable source (one random friend), but again didn't really care.

About the bug with the divisions, I still don't want to continue working on this plugin actively, but if anyone wants to contribute, I'm happy to review changes and update the plugin. 

Since I'm not going to look into it myself, if you think I should remove the disclaimer on the plugin page, I will.

Sorry I couldn't be more helpful.

**Comment by Imsvale** [comment]
That's alright, I understand. :) I'll await more feedback from others to confirm. I'll let you know.

**Comment by Imsvale** [comment]
Ah, I can confirm already. No ratings have changed. The story is during the development of this plugin you saw a lot of changes, for seasons 1, 2 and 3. You probably figured that would continue. But no ratings have changed since then. That was just unfortunate timing. The linked chart is accurate, for what it's worth. Thanks to [u/HoraryHellfire2](https://www.reddit.com/user/HoraryHellfire2) for confirming, pretty much the most reputable source outside of Psyonix you're ever going to find.

In my judgment it is now very safe to remove the disclaimer.

**Comment by Imsvale** [comment]
Resolved.

**Comment by BenTheDan** [comment]
Thank you, I really appreciate you taking the time to look into this.
The disclaimer is now removed.

**Comment by Imsvale** [comment]
No worries. I like the plugin, and this is something I felt I could assist with, so why not. :) Thanks for making it!
