### ISSUE TITLE
Ranks show assigned to wrong people at start of the match

### ISSUE THREAD

**Issue by mmotti** [BenTheDan/IngameRank#3]
**This has only been tested in Casual as I don't play a lot of competitive.**

Just installed this plugin today and noticed that at the start of the matches the ranks do not seem to display correctly, or rather the correct ranks are visible but next to the wrong persons.  It seems to resolve itself later into the game but can be a little confusing.

Settings are left on default; showing "best" rank across playlists. The only change I've made is disabling divisions.

**Start of match**
![Incorrect - Start of match](https://user-images.githubusercontent.com/35599110/185975262-9358547c-5324-4e13-81f0-56d1ee91d04e.png)

**Later in match**
![Correct - Some time into match](https://user-images.githubusercontent.com/35599110/185975266-b1ce605c-50f6-47df-9579-45b3db9a59a0.png)

**Comment by BenTheDan** [comment]
Hey,

Thanks for reaching out!
I know about the issue, and from what I remember, it is due to the plugin assuming alphabetical order on the start, while it may be by order of joining or just random.
It later corrects itself because it orders them by score.
But at the start of the match everyone is at 0.
Unfortunatelly I don't have a sollution to the problem, and I've stopped working on this plugin long ago. 
However the repository is open to contributions, so if you or anyone else has a fix I'm happy to update the plugin.

**Comment by nkezhaya** [comment]
@BenTheDan still alive and accepting PRs? 😄 Might work on this this week.

**Comment by BenTheDan** [comment]
@nkezhaya alive and well 😀, if you'd like to submit a PR I'm happy to review it and add it to the plugin

**Comment by BenTheDan** [comment]
Fixed in the v1.2.1 patch (still pending review)
