### ISSUE TITLE
Playlist not showing

### ISSUE THREAD

**Issue by MontageTM** [BenTheDan/IngameRank#7]
The playlist that the rank is in only shows up if you have selected the playlist "Best".  However, it doesn not show if you have any other playlist selected. This might not be a problem if you always have the same playlist selected and you remember which one you've chosen,  but if I am cycling through the playlists while in game to see my opponents or teammates ranks in different gamemodes, its frustrating I cant see which is which. :D

**Comment by nkezhaya** [comment]
@MontageTM I agree! I think this could be fixed here:

https://github.com/BenTheDan/IngameRank/blob/main/source/IngameRank.cpp#L254

Just changing:

```cpp
if (show_playlist && playlist == 0 && isSynced) {
```

to:

```cpp
if (show_playlist && isSynced) {
```

**Comment by Otiel** [comment]
@BenTheDan Any chance you release a new version with the fix mentionned by @nkezhaya?

**Comment by BenTheDan** [comment]
Hey,

I'm probably a bit late to the party, but I came back to patch the plugin and going through the issues.
What you're describing is by design. The playlists next to the players only show up when Best is selected in order to show which playlist the best rank is from.
When a specific playlist is selected all the players would have the same image next to them, which carries no useful information and is a visual distraction.
However the playlist selection is displayed in the top right corner of the screen whenever you open the scoreboard. You can look up there if you ever forget your selection.

Hope I could help!
